apiVersion: v1
kind: Pod
metadata:
 name: component-python-document-pycco
spec:
 containers:
 - name: pycco
   image: hub.opshub.sh/containerops/pycco:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/pycco-docs/pycco.git"
   resources:
     requests:
       cpu: 4
       memory: 8G
 restartPolicy: Never
