# Copyright 2016 - 2017 Huawei Technologies Co., Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: cncf/python-for-cncf-ci/build-test-release-deploy
number: 33
title: Components For Python
version: 4
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: prometheus-test-build-release-python-ci-components
    title: Building, testing python project, compile then upload to Dockyard artifact repository.
    sequencing: sequence
    actions:
      -
        name: build-python-analysis-coala
        title: Build python project with "make build"
        jobs:
          -
            type: component
            kubectl: python/test.yaml
            endpoint: hub.opshub.sh/containerops/analysis_java_gradle_checkstyle
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=json"
      -
  -
    type: end
    name: end
    title: End
