apiVersion: v1
kind: Pod
metadata:
 name: component-python-analysis-memory-profiler
spec:
 containers:
 - name: memory_profiler
   image: hub.opshub.sh/containerops/memory_profiler:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/fabianp/memory_profiler.git entry-file=test/test_func.py"
   resources:
     requests:
       cpu: 4
       memory: 8G
 restartPolicy: Never
