uri: containerops/component/python-component-pylint-test
title: Component for python projects
version: 1
tag: latest
timeout: 0
receivers:
  -
    type: mail
    address: lidian@containerops.sh
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: analysis-python-component
    title:  Component analysis action
    sequencing: sequence
    actions:
      -
        name: component-python-analysis-pylint-action1
        title: _[Pylint](https://github.com/PyCQA/pylint) is a Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells (as defined in Martin Fowler's Refactoring book).
        jobs:
          -
            type: component
            kubectl: component-python-analysis-pylint.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-pylint:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git"
      -
        name: component-python-analysis-pylint-action2
        title: _[Pylint](https://github.com/PyCQA/pylint) is a Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells (as defined in Martin Fowler's Refactoring book).
        jobs:
          -
            type: component
            kubectl: component-python-analysis-pylint.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-pylint:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git out-put-type=yaml"
      -
        name: component-python-analysis-pylint-action3
        title: _[Pylint](https://github.com/PyCQA/pylint) is a Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells (as defined in Martin Fowler's Refactoring book).
        jobs:
          -
            type: component
            kubectl: component-python-analysis-pylint.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-pylint:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git out-put-type=yaml version=python"
      -
        name: component-python-analysis-pylint-action4
        title: _[Pylint](https://github.com/PyCQA/pylint) is a Python source code analyzer which looks for programming errors, helps enforcing a coding standard and sniffs for some code smells (as defined in Martin Fowler's Refactoring book).
        jobs:
          -
            type: component
            kubectl: component-python-analysis-pylint.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-pylint:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/Lupino/python-aio-periodic.git version=python"
      -
  -
    type: end
    name: end
    title: End
