apiVersion: v1
kind: Pod
metadata:
 name: component-python-analysis-pylint
spec:
 containers:
 - name: pylint
   image: hub.opshub.sh/containerops/pylint:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/Lupino/python-aio-periodic.git"
   resources:
     requests:
       cpu: 4
       memory: 8G
 restartPolicy: Never
