apiVersion: v1
kind: Pod
metadata:
 name: component-python-analysis-coala
spec:
 containers:
 - name: coala
   image: hub.opshub.sh/containerops/coala:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/Lupino/python-aio-periodic.git"
   resources:
     requests:
       cpu: 4
       memory: 8G
 restartPolicy: Never
