      -
        name: {{.}}
        title: Build python project with "make build"
        jobs:
        -
           type: component
           kubectl: python/test.yaml
           endpoint: hub.opshub.sh/containerops/{{.}}
           resources:
             cpu: 2
             memory: 4G
           timeout: 0
           environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=json"
      -
