      -
        name: build-python-analysis-coala
        title: Build python project with "make build"
        jobs:
        -
           type: component
           kubectl: python/test.yaml
           endpoint: {{.}}hub.opshub.sh/containerops/analysis_java_gradle_checkstyle
           resources:
             cpu: 2
             memory: 4G
           timeout: 0
           environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=json"
      -
