name: cncf/python-for-cncf-ci/build-test-release-deploy
number: 33
title: Components For Python
version: 4
tag: latest
timeout: 0
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: prometheus-test-build-release-python-ci-components
    title: Building, testing python project, compile then upload to Dockyard artifact repository.
    sequencing: sequence
    actions:
      -
        name: build-python-analysis-coala
        title: Build python project with \"make build\"
        jobs:
        -
           type: component
           kubectl: python/test.yaml
           endpoint: hub.opshub.sh/containerops/analysis_java_gradle_checkstyle
           resources:
             cpu: 2
             memory: 4G
           timeout: 0
           environments:
              - CO_DATA: \"version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=json\"
      -
  -
    type: end
    name: end
    title: End
