apiVersion: v1
kind: Pod
metadata:
 name: phpcpd-test
spec:
 containers:
 - name: phpcpd
   image: hub.opshub.sh/containerops/analysis_php_phpcpd:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/TIGERB/easy-php.git"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never