apiVersion: v1
kind: Pod
metadata:
 name: compile-java-gradle-jar
spec:
 containers:
 - name: compile-java-gradle-jar
   image: hub.opshub.sh/containerops/compile-java-gradle-jar
   env:
   - name: CO_DATA
     value: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git target=https://hub.opshub.sh/binary/v1/containerops/component/binary/2.2.4/demo.jar"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never