apiVersion: v1
kind: Pod
metadata:
 name: compile-java-gradle-war
spec:
 containers:
 - name: compile-java-gradle-war
   image: hub.opshub.sh/containerops/compile-java-gradle-war
   env:
   - name: CO_DATA
     value: "version=gradle3 git-url=https://github.com/rominirani/GradleWebAppSample.git target=https://hub.opshub.sh/binary/v1/lidian/test/binary/2.2.4/web.war"
   resources:
     requests:
       cpu: 2
       memory: 4G
 restartPolicy: Never