uri: containerops/component/java-gradle-analysis-pmd
title: Component for java gradle project with composer
version: 1
tag: latest
timeout: 0
receivers:
  -
    type: mail
    address: hubopsnotifier@gmail.com
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: analysis-java-gradle-pmd
    title: source code analyzer PMD can finds common programming flaws
    sequencing: sequence
    actions:
      -
        name: java-gradle-pmd-action1
        title: source code analyzer PMD can finds common programming flaws
        jobs:
          -
            type: component
            kubectl: component-java-gradle-analysis-pmd.yaml
            endpoint: hub.opshub.sh/containerops/analysis-java-gradle-pmd:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/vanniuner/gradle-demo.git"
      -
        name: java-gradle-pmd-action2
        title: source code analyzer PMD can finds common programming flaws
        jobs:
          -
            type: component
            kubectl: component-java-gradle-analysis-pmd.yaml
            endpoint: hub.opshub.sh/containerops/analysis-java-gradle-pmd:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=json"
      -
        name: java-gradle-pmd-action3
        title: source code analyzer PMD can finds common programming flaws
        jobs:
          -
            type: component
            kubectl: component-java-gradle-analysis-pmd.yaml
            endpoint: hub.opshub.sh/containerops/analysis-java-gradle-pmd:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "version=gradle3 git-url=https://github.com/vanniuner/gradle-demo.git out-put-type=xml"
  -
    type: end
    name: end
    title: End