apiVersion: v1
kind: Pod
metadata:
 name: component-python-analysis-line-profiler
spec:
 containers:
 - name: line_profiler
   image: hub.opshub.sh/containerops/line_profiler:latest
   env:
   - name: CO_DATA
     value: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py"
   resources:
     requests:
       cpu: 4
       memory: 8G
 restartPolicy: Never
