uri: containerops/component/python-component-line-profiler-test
title: Component for python projects
version: 1
tag: latest
timeout: 0
receivers:
  -
    type: mail
    address: lidian@containerops.sh
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: analysis-python-component
    title:  Component analysis action
    sequencing: sequence
    actions:
      -
        name: component-python-analysis-line-profiler-action1
        title: _[line_profiler](https://github.com/rkern/line_profiler) is a module for doing line-by-line profiling of functions.
        jobs:
          -
            type: component
            kubectl: component-python-analysis-line-profiler.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-line-profiler:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py"
      -
        name: component-python-analysis-line-profiler-action2
        title: _[line_profiler](https://github.com/rkern/line_profiler) is a module for doing line-by-line profiling of functions.
        jobs:
          -
            type: component
            kubectl: component-python-analysis-line-profiler.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-line-profiler:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py out-put-type=yaml"
      -
        name: component-python-analysis-line-profiler-action3
        title: _[line_profiler](https://github.com/rkern/line_profiler) is a module for doing line-by-line profiling of functions.
        jobs:
          -
            type: component
            kubectl: component-python-analysis-line-profiler.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-line-profiler:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py version=python"
      -
        name: component-python-analysis-line-profiler-action4
        title: _[line_profiler](https://github.com/rkern/line_profiler) is a module for doing line-by-line profiling of functions.
        jobs:
          -
            type: component
            kubectl: component-python-analysis-line-profiler.yaml
            endpoint: hub.opshub.sh/containerops/component-python-analysis-line-profiler:latest
            resources:
              cpu: 4
              memory: 8G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/istrategylabs/python-profiling entry-file=debug.py out-put-type=yaml version=python"
      -
  -
    type: end
    name: end
    title: End
